monit_services:
  - name: blog.entwicklerbier.org
    type: system
    rules:
      - "if memory usage > 90% for 3 cycles then alert"
      - "if swap usage > 70% for 3 cycles then alert"
      - "if cpu usage (user)   > 70% then alert"
      - "if cpu usage (system) > 30% then alert"
      - "if cpu usage (wait)   > 20% then alert"
  - name: /
    target: "{{ ansible_mounts[0].device }}"
    type: filesystem
    rules:
      - "if space usage > 80% for 8 cycles then alert"

  - name: apache
    type: process
    target: /var/run/apache2/apache2.pid
    start: /etc/init.d/apache2 start
    stop: /etc/init.d/apache2 stop
    rules:
    -  "if totalcpu > 80% for 3 cycles then alert"
    -  "if totalcpu > 80% for 6 cycles then restart"
  - name: mysql
    type: process
    target: /var/run/mysqld/mysqld.pid
    start: "/etc/init.d/mysql start"
    stop: "/etc/init.d/mysql stop"
    rules:
    -  "if totalcpu > 80% for 3 cycles then alert"
    -  "if totalcpu > 80% for 6 cycles then restart"
